module top(
    input CLOCK_50,

    // Physical VGA Pins on the DE2-115
    output VGA_HS,
    output VGA_VS,
    output VGA_BLANK_N,
    output VGA_SYNC_N,
    output VGA_CLK,
    output [9:0] VGA_R,
    output [9:0] VGA_G,
    output [9:0] VGA_B
);

    // =========================================================
    // 1. HARDCODED GAME STATE (Dummy Inputs for Testing)
    // =========================================================
    // We lock the players in place so the graphics module 
    // has fixed coordinates to draw on the screen.
    
    wire [9:0] p1_x     = 10'd230;
    wire [9:0] p1_y     = 10'd240;
    wire [3:0] p1_state = 4'd0;
    wire [2:0] p1_frame = 3'd0;
    wire [7:0] p1_hp    = 8'd50; 

    wire [9:0] p2_x     = 10'd345;
    wire [9:0] p2_y     = 10'd240;
    wire [3:0] p2_state = 4'd0;
    wire [2:0] p2_frame = 3'd0;
    wire [7:0] p2_hp    = 8'd25; 

    // =========================================================
    // 2. ROM WIRES (The copper traces connecting the chips)
    // =========================================================
    wire [16:0] p1_rom_addr, p2_rom_addr;
    wire [14:0] bg_rom_addr;

    wire [7:0] p1_rom_data;
    wire [7:0] p2_rom_data;
    wire [7:0] bg_rom_data;

    // =========================================================
    // 3. THE HARDWARE ROMS (Generated by Quartus GUI)
    // =========================================================
    // Make sure these names match exactly what you typed 
    // into the Quartus IP Catalog wizard!

    p1_sprite_rom player1_memory (
        .address (p1_rom_addr),  // Graphics module asks for an address
        .clock   (CLOCK_50),
        .q       (p1_rom_data)   // ROM sends back the 8-bit color
    );

    p2_sprite_rom player2_memory (
        .address (p2_rom_addr),
        .clock   (CLOCK_50),
        .q       (p2_rom_data)
    );

    bg_sprite_rom background_memory (
        .address (bg_rom_addr),
        .clock   (CLOCK_50),
        .q       (bg_rom_data)
    );

    // =========================================================
    // 4. CALLING YOUR GRAPHICS MODULE
    // =========================================================
    graphics my_graphics (
        .CLOCK_50   (CLOCK_50),

        // Feeding it the dummy game logic
        .p1_x       (p1_x),
        .p1_y       (p1_y),
        .p1_state   (p1_state),
        .p1_frame   (p1_frame),
        .p1_hp      (p1_hp),

        .p2_x       (p2_x),
        .p2_y       (p2_y),
        .p2_state   (p2_state),
        .p2_frame   (p2_frame),
        .p2_hp      (p2_hp),

        // Plugging the ROM wires into the graphics engine
        .p1_rom_addr(p1_rom_addr),
        .p2_rom_addr(p2_rom_addr),
        .p1_rom_data(p1_rom_data),
        .p2_rom_data(p2_rom_data),
        
        .bg_rom_addr(bg_rom_addr),
        .bg_rom_data(bg_rom_data),

        // Outputting straight to the physical VGA pins
        .VGA_HS     (VGA_HS),
        .VGA_VS     (VGA_VS),
        .VGA_BLANK_N(VGA_BLANK_N),
        .VGA_SYNC_N (VGA_SYNC_N),
        .VGA_CLK    (VGA_CLK),
        .VGA_R      (VGA_R),
        .VGA_G      (VGA_G),
        .VGA_B      (VGA_B)
    );

endmodule